import Head from "next/head";
import Intro from "src/components/introduction";
import LoginForm from "src/components/forms/user/login-form";

/**
 * Home component serves as the landing page for the application.
 *
 * It sets up the page header with meta information and renders the introduction
 * and login form components as the main content.
 *
 * @returns {JSX.Element} The rendered home page component.
 */
export default function Home() {
  return (
    <>
      {/* Set up the document head with title, meta tags, and favicon */}
      <Head>
        <title>Exams-platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Display the introduction component */}
      <Intro />
      {/* Display the login form */}
      <LoginForm />
    </>
  );
}
