import Head from 'next/head'
import UserContainer from '../components/user/container'


export default function Home() {
  return (
    <>
      <Head>
        <title>Exams-platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-full w-full '>
        
          <UserContainer />
        
      </main>
    </>
  )
}
