import Head from 'next/head'
import styles from '../styles/Home.module.css'



export default function Home() {
  return (
    <>
      <Head>
        <title>Exams-platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div id="container" className='text-red-500'>
          <h1>welcome to Exams-platform</h1>
        </div>
      </main>
    </>
  )
}
