import Head from 'next/head'
import Intro from '../components/introduction'
import UserForm from '../components/userForm'
import question from '../src/models/questions/example'

export default function Home() {
  //console.log(question)
  return (
    <>
      <Head>
        <title>Exams-platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-full w-full '>
        
          <Intro />
          <UserForm   />
        
      </main>
    </>
  )
}
